###
POST http://localhost:3000/api/transaksi

{
          "thang"  : "2023", 
          "periode" : "31", 
          "kdkppn" : "010",
          "kdpemda" : "0800", 
          "potongan" : 1000080,
          "KDAKUN" : 817714
}
###
GET  http://localhost:3000/api/transaksi

###
PUT http://localhost:3000/api/transaksi?id=1

{
          "thang"  : "2023", 
          "periode" : "32", 
          "kdkppn" : "001",
          "kdpemda" : "0600", 
          "potongan" : 1000099,
          "KDAKUN" : 817714
}

###

DELETE http://localhost:3000/api/transaksi?id=1

###
POST http://localhost:3000/api/transaksi

{
          "thang"  : "", 
          "periode" : "", 
          "kdkppn" : "",
          "kdpemda" : "", 
          "potongan" : "",
          "KDAKUN" : ""
}

###
# Test Response API Renkas
POST http://localhost:3000/api/renkas

{
          "kdsatker"  : "500213", 
          "kdkppn" : "104", 
          "kdjenis" : "01",
          "periode" : "01", 
          "renkas" : 899000
}

###
GET http://localhost:3000/api/renkas

###
PUT http://localhost:3000/api/renkas?id=5

{
          "kdsatker"  : "500213", 
          "kdkppn" : "104", 
          "kdjenis" : "01",
          "periode" : "01", 
          "renkas" : 499000
}

###
DELETE http://localhost:3000/api/renkas?id=4